### PR TITLE
fixing two high vulnerabilities

### PR DESCRIPTION
**Pull request by patrick-fs**
ran `npm audit fix`

### CODE REVIEW

**Review by sabrina-li — APPROVED** [review]
LGTM

**Comment by patrick-fs** [comment]
Circle CI status reporting is stuck for several days. Going to close and repoen in the hope that it jolts it free:

image

**Comment by patrick-fs** [comment]
Rerunning pipeline from CircleCI didn't work either. Check will not pass even though it is green in CircleCI:

image

**Comment by patrick-fs** [comment]
For posterity: I re-ran status checks and I was able to find the `test-deploy` workflow, whereas the prior status check was pegged to the related `build-browser-sdk` job.

Not sure what happened and if CircleCI might have started reporting status checks to GH differently.

Anyhoo - will keep an eye out on this.

**Pull request merged**
